{{ config(materialized='table') }}

select  TABLE_NAME,TABLE_SCHEMA AS SCHEMA, TABLE_CATALOG AS DATABASE, CREATED, LAST_ALTERED
from
"SNOWFLAKE"."ACCOUNT_USAGE"."TABLES"
where  DELETED is null and TABLE_TYPE = 'BASE TABLE'
